### ISSUE TITLE
Circuit Diagram revision

### ISSUE THREAD

**Issue by ashinckley** [victor-chew/filament-joiner#2]
I wasn't able to get the OLED to work in the configuration illustrated in the circuit diagram.
I was able to get it to work by connecting SDA to A4 and SCL to A5 for the Arduino Nano.  

I was also not able to get the rotary encoder to work without connecting the + pin to 5V.

**Comment by victor-chew** [comment]
I re-checked the schematic with my physical circuit, and you are right on both counts.

I have updated the circuit diagram after fixing both errors.

Thanks for pointing them out!

**Comment by ashinckley** [comment]
No worries.  Great project!  I'm currently trying to debug my thermistor values measuring at -273C, but I think my thermistor just might be toast.

**Comment by ashinckley** [comment]
> 

Yup.  The thermistor was dead.  Replaced it and the device is working.  Thanks for the design!
